### ISSUE TITLE
styling looks off

### ISSUE THREAD

**Issue by jhoogeboom** [YU000jp/logseq-plugin-quickly-para-method#22]
Do I need a certain theme for this?

<img width="413" alt="Screenshot 2023-11-06 at
 13 20 53" src="https://github.com/YU000jp/logseq-plugin-quickly-para-method/assets/1828504/ef767aa8-4103-4f64-ad57-44788a7eeee4">

it looks a lot better in your preview
![image-1](https://github.com/YU000jp/logseq-plugin-quickly-para-method/assets/1828504/94fc20fd-4759-4173-a799-4bff4ffce093)

**Comment by YU000jp** [comment]
Thanks. That's what was happening. I didn't notice it until you pointed it out because it was different from developer mode.
I released a new version. Please update.

**Comment by jhoogeboom** [comment]
Looks good now, thanks!
