### ISSUE TITLE
"/Resources" appends comma to end of first block

### ISSUE THREAD

**Issue by jwhonce** [YU000jp/logseq-plugin-quickly-para-method#25]
The command correctly adds `Resources` to the `tags::` property as expected, additionally it appends an unexpected comma to the end of the block. The `Resources` page is updated as expected.

Page Properties:
```
tags:: associate
github-id:: 
gitlab-id:: 
jira-id:: 
```

After `/Resources` command:
```
tags:: associate, Resources
github-id:: 
gitlab-id:: 
jira-id::,
```
Notice tailing comma.

**Comment by YU000jp** [comment]
It is a bug. The use of "," was to address a bug that prevented page-tags from being updated.

**Comment by YU000jp** [comment]
Change:
* [x] Insert tags property using analog techniques. Instead of Logseq API.

I released a new version. Try it, please. It is not yet known whether this bug has been completely resolved for each condition.

**Comment by jwhonce** [comment]
Using plugin v1.8.6 and logseq 0.10.8
```
tags:: 
page-type:: [[Projects]] 
architect:: 
lead:: 
github-url:: 
deadline:: 
priority:: #A
marker:: DOING
tags:: Projects,
```

The `tags::` property was duplicated.

**Comment by YU000jp** [comment]
> Using plugin v1.8.6 and logseq 0.10.8
> ```
> tags:: 
> page-type:: [[Projects]] 
> architect:: 
> lead:: 
> github-url:: 
> deadline:: 
> priority:: #A
> marker:: DOING
> tags:: Projects,
> ```
> 
> The `tags::` property was duplicated.

Thank you for reporting this. It seems that the plugin API failed to delete the property and it was duplicated. I will fix it.

**Comment by jwhonce** [comment]
Happy to help test.

**Comment by YU000jp** [comment]
I can't reproduce it properly. If "tags::" occurs temporarily and the value is empty, please delete it manually.

**Comment by jwhonce** [comment]
My steps:

1. I create empty page
2. Apply one of my /Template's (which has page properties with tags::)
3. /Page-Tag (Resources)

**Comment by YU000jp** [comment]
I see. In your usage, you create an empty property "tags::" for input in the template, right?

**Comment by jwhonce** [comment]
`tags::` has one value I use in queries.

**Comment by YU000jp** [comment]
> `tags::` has one value I use in queries. I suspect with a little thought, I could use page-type for my meta-data and leave tags for your plugin.

You want to use "page-type::" instead of "tags::"? If consistency can be achieved, it may be possible to make "specifying the property-name" an option.
